# Generated by Django 4.0.4 on 2024-05-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='shape_type',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle')], max_length=10),
        ),
    ]
