# Generated by Django 4.0.4 on 2024-05-25 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawings', '0002_alter_shape_shape_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='shape_type',
            field=models.CharField(blank=True, choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('star', 'Star')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shape',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
